### PR TITLE
Remove unwanted fields; process global_workqueue workByStatus; added dry-run option

### PR DESCRIPTION
**Pull request by amaltaro**
Summary of changes are:
* added a `--dry-run` option to run this script without injecting anything into ES/MONIT
* removed some unwanted/couch fields
* fixed `site_info` docs, metrics under `LocalWQ_INFO`
* print a summary of number of docs injected (or not, dry-run) into AMQ
* exception for `global_workqueue` metrics, create `work_info` docs
* exception for `global_workqueue` metrics, create `site_info` docs
* (breaking change) remove `WMBS_INFO` key from site_info docs

the rest is only aesthetic changes.
@stiegerb please review.
I've run several tests on dry-run mode, checked the output, data type/etc and everything looks Ok. If you agree, can you please merge and deploy this script?

### CODE REVIEW

**Comment by amaltaro** [comment]
See http://amaltaro.web.cern.ch/amaltaro/forBenjamin/struct
for the breaking changes on the data structure.

**Comment by stiegerb** [comment]
Looks good to me. The `--dry-run` might be a bit verbose, but ok.

**Comment by amaltaro** [comment]
should I set those prints to logging.debug instead? Indeed it's very verbose

**Comment by amaltaro** [comment]
@stiegerb I pushed a 3rd commit to fix those prints. If you agree, I can squash it and you can merge it.

**Comment by stiegerb** [comment]
Looks good. Go ahead and squash them and I merge

**Pull request merged**
